using CampaignService.Common.Entities;
using System;

namespace CampaignService.Data.Models
{
    public class OrderModel : EntityBaseModel
    {
        public Guid OrderGuid { get; set; }
        public int StoreId { get; set; }
        public int CustomerId { get; set; }
        public int BillingAddressId { get; set; }
        public int? ShippingAddressId { get; set; }
        public bool PickUpInStore { get; set; }
        public int OrderStatusId { get; set; }
        public int ShippingStatusId { get; set; }
        public int PaymentStatusId { get; set; }
        public string PaymentMethodSystemName { get; set; }
        public string CustomerCurrencyCode { get; set; }
        public decimal CurrencyRate { get; set; }
        public int CustomerTaxDisplayTypeId { get; set; }
        public string VatNumber { get; set; }
        public decimal OrderSubtotalInclTax { get; set; }
        public decimal OrderSubtotalExclTax { get; set; }
        public decimal OrderSubTotalDiscountInclTax { get; set; }
        public decimal OrderSubTotalDiscountExclTax { get; set; }
        public decimal OrderShippingInclTax { get; set; }
        public decimal OrderShippingExclTax { get; set; }
        public decimal PaymentMethodAdditionalFeeInclTax { get; set; }
        public decimal PaymentMethodAdditionalFeeExclTax { get; set; }
        public string TaxRates { get; set; }
        public decimal OrderTax { get; set; }
        public decimal OrderDiscount { get; set; }
        public decimal OrderTotal { get; set; }
        public decimal RefundedAmount { get; set; }
        public bool RewardPointsWereAdded { get; set; }
        public string CheckoutAttributeDescription { get; set; }
        public string CheckoutAttributesXml { get; set; }
        public int CustomerLanguageId { get; set; }
        public int AffiliateId { get; set; }
        public string CustomerIp { get; set; }
        public bool AllowStoringCreditCardNumber { get; set; }
        public string CardType { get; set; }
        public string CardName { get; set; }
        public string CardNumber { get; set; }
        public string MaskedCreditCardNumber { get; set; }
        public string CardCvv2 { get; set; }
        public string CardExpirationMonth { get; set; }
        public string CardExpirationYear { get; set; }
        public string PaymentCardName { get; set; }
        public string PaymentBankName { get; set; }
        public string PaymentGatewayName { get; set; }
        public string PaymentInstallmentCount { get; set; }
        public string PaymentTypeErpCode { get; set; }
        public string AuthorizationTransactionId { get; set; }
        public string AuthorizationTransactionCode { get; set; }
        public string AuthorizationTransactionResult { get; set; }
        public string CaptureTransactionId { get; set; }
        public string CaptureTransactionResult { get; set; }
        public string SubscriptionTransactionId { get; set; }
        public DateTime? PaidDateUtc { get; set; }
        public string ShippingMethod { get; set; }
        public string ShippingRateComputationMethodSystemName { get; set; }
        public string CustomValuesXml { get; set; }
        public bool Deleted { get; set; }
        public DateTime CreatedOnUtc { get; set; }
        public string BukoliInvoiceNo { get; set; }
        public int? FraudStatusId { get; set; }
        public string OrderNote { get; set; }
        public string GiftNote { get; set; }
        public bool? IsExported { get; set; }
        public DateTime? ExportedOnUtc { get; set; }
        public string ErpCode { get; set; }
        public string BillingNumber { get; set; }
        public int? OrderTypeId { get; set; }
        public bool? Is3Dorder { get; set; }
        public bool? IsMobileOrder { get; set; }
        public string RelatedReferral { get; set; }
        public string OrderNumber { get; set; }
        public string ReturnOrderTrackingNumber { get; set; }
        public string LoyaltyCardNumber { get; set; }
        public string SmsverificationCode { get; set; }
        public bool? IsImpersonated { get; set; }
        public int? ImpersonatedById { get; set; }
        public int? ImpersonatedStoreId { get; set; }
        public int? ImpersonatedStaffId { get; set; }
        public decimal PaymentMethodAdditionalFeePercent { get; set; }
        public DateTime? ReturnedOnUtc { get; set; }
        public string PhysicalStorePosDeviceId { get; set; }
        public int? ErpStatusId { get; set; }
        public string ErpTransactionCode { get; set; }
        public DateTime? ErpTransactionDate { get; set; }
        public string ErpInvoiceNumber { get; set; }
        public string ErpCode2 { get; set; }
        public string OrderErpInformation { get; set; }
        public decimal OrderFreight { get; set; }
        public decimal UsedLoyaltyPointTotal { get; set; }
        public string PaymentCurrencyCode { get; set; }
        public string CargoLineId { get; set; }
        public string ReturnBillingNumber { get; set; }
        public DateTime? ReturnExportedOnUtc { get; set; }
        public string ReturnOrderErpInformation { get; set; }
        public string CheckOutSessionValue { get; set; }
        public decimal PaymentMethodUsedPoint { get; set; }
        public decimal UsedLoyaltyPointMultiplir { get; set; }
        public decimal UsedLoyaltyPointMultiplier { get; set; }
        public string InvoiceUrl { get; set; }
        public string DeliveryBarcode { get; set; }
    }
}
